version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=AlloBrain
    volumes:
      - mongo_data:/data/db 


  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=adminuser
      - ME_CONFIG_BASICAUTH_PASSWORD=adminpasswd
    depends_on:
      - mongodb

  notes_backend:
    build: ./backend
    ports:
      - "6173:6173"
    environment:
      - DB_CONNEXION_STRING=mongodb://admin:password@mongodb:27017
      - DATABASE=AlloBrain
    depends_on:
      - mongodb

  notes_frontend:
    build: ./frontend
    ports:
      - "7173:7173"
    depends_on:
      - notes_backend


volumes:
  mongo_data:  
    driver: local