version: "3"
services:
  mongodb:
    image: mongo
    command: mongod --port ${MONGO_PORT}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - mongo_data:/data/db 

  mongo-express:
    image: mongo-express
    ports:
      - "${ME_PORT}:${ME_PORT}"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:${MONGO_PORT}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_PASSWORD}
    depends_on:
      - mongodb

  notes_backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - DB_CONNEXION_STRING=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:${MONGO_PORT}
      - DATABASE=${MONGO_DATABASE}
    command: ["uvicorn", "src.main:app", "--port", "${BACKEND_PORT}", "--host", "0.0.0.0"] 
    depends_on:
      - mongodb

  notes_frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:    
      - VITE_BACKEND_URL=http://127.0.0.1:${BACKEND_PORT}
    command: ["npm", "run", "dev", "--", "--host", "--port", "${FRONTEND_PORT}"]
    depends_on:
      - notes_backend


volumes:
  mongo_data:  
    driver: local